export const SET_ALERT = 'SET_ALERT';
export const CLEAR_ALERTS = 'CLEAR_ALERTS';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCESS';
export const UPDATE_USER = 'UPDATE_USER';
export const UPDATE_USER_PHOTO = 'UPDATE_USER_PHOTO';

export const MESSAGES_LOADING = 'MESSAGES_LOADING';
export const MESSAGES_LOADED = 'MESSAGES_LOADED';
export const SET_CURRENT_MESSAGE = 'SET_CURRENT_MESSAGE';
export const SEND_MESSAGE = 'SEND_MESSAGE';
export const UPDATE_MESSAGE = 'UPDATE_MESSAGE';
export const DELETE_MESSAGE = 'DELETE_MESSAGE';

export const REVIEWS_LOADING = 'REVIEWS_LOADING';
export const REVIEWS_LOADED = 'REVIEWS_LOADED';
export const REVIEW_LOADING = 'REVIEW_LOADING';
export const REVIEW_LOADED = 'REVIEW_LOADED';
export const ADD_REVIEW = 'ADD_REVIEW';
export const ADD_COMMENT = 'ADD_COMMENT';

export const GET_USERS = 'GET_USERS';
export const GET_USER = 'GET_USER';
export const FETCH_USER = 'FETCH_USER';
